# vim: ft=yaml.ansible
---
- name: Prepare installation
  hosts: localhost
  tasks:
    - name: Generate temporary SSH keypair for installation
      community.crypto.openssh_keypair:
        path: '{{ playbook_dir }}/archiso_ssh.key'
        size: 384
        type: ecdsa
      register: install_ssh_key

    - name: Generate service account SSH keypair
      community.crypto.openssh_keypair:
        path: '{{ playbook_dir }}/service_account.key'
        size: 384
        type: ecdsa

    - name: Start ephemeral PXE server
      ansible.builtin.import_role:
        name: homelab.netinstall.pxe_server
        tasks_from: start
      vars:
        pxe_server_ssh_authorized_key: '{{ install_ssh_key.public_key }}'

    - name: Start ephemeral pacman proxy
      ansible.builtin.import_role:
        name: homelab.netinstall.pacoloco
        tasks_from: start

- name: Install OS on nodes
  hosts: nodes
  gather_facts: false # delayed until after we woke up the target
  tasks:
    - name: Wake up nodes
      community.general.wakeonlan:
        mac: '{{ mac }}'
      delegate_to: localhost

    - name: Wait for node to be reachable
      ansible.builtin.wait_for_connection:
        connect_timeout: 1
        timeout: 600

    - name: Gather facts
      ansible.builtin.setup:

    - name: Start installation
      ansible.builtin.import_role:
        name: homelab.netinstall.archlinux_setup
      vars:
        archlinux_setup_disk_boot: '{{ disks["boot"] }}'
        archlinux_setup_pacman_proxy:
          enabled: true
          mirror: http://192.168.1.65:9129/repo/archlinux/$repo/os/$arch
        archlinux_setup_ansible_account_ssh_authorized_key: '{{ lookup("file", playbook_dir + "/service_account.key.pub") }}'

    - name: Shutdown nodes
      become: true
      community.general.shutdown:

- name: Cleanup installation
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Stop ephemeral pacman proxy
      ansible.builtin.import_role:
        name: homelab.netinstall.pacoloco
        tasks_from: stop

    - name: Stop ephemeral PXE server
      ansible.builtin.import_role:
        name: homelab.netinstall.pxe_server
        tasks_from: stop

    - name: Delete temporary SSH keypair
      ansible.builtin.file:
        path: '{{ item }}'
        state: absent
      loop:
        - '{{ install_ssh_key.filename }}'
        - '{{ install_ssh_key.filename }}.pub'

