# vim: ft=yaml.ansible
---
- name: Prepare installation
  hosts: localhost
  tasks:
    - name: Start ephemeral PXE server
      ansible.builtin.import_role:
        name: pxe_server
        tasks_from: start

- name: Install OS on nodes
  hosts: all
  gather_facts: false # delayed until after we woke up the target
  tasks:
    - name: Wake up nodes
      community.general.wakeonlan:
        mac: '{{ mac }}'
      delegate_to: localhost

    - name: Wait for node to be reachable
      ansible.builtin.wait_for_connection:
        connect_timeout: 1
        timeout: 600

    - name: Gather facts
      ansible.builtin.setup:

    - name: Setup boot drive
      become: true
      ansible.builtin.import_role:
        name: disk_setup
      vars:
        disk_setup_spec: '{{ disk_layout }}'

    # - name: Generate NixOS config
    #   become: true
    #   ansible.builtin.command:
    #     cmd: nixos-generate-config --root /mnt
    #     creates: /mnt/etc/nixos/hardware-configuration.nix

    # Workaround the shutdown module not using the $PATH
    - name: Find shutdown command path # noqa: risky-shell-pipe
      ansible.builtin.shell:
        cmd: 'dirname $(whereis -b shutdown | cut -d" " -f2)'
        creates: # nothing
      register: shutdown_path

    # - name: Shutdown nodes
    #   become: true
    #   community.general.shutdown:
    #     search_paths: ['{{ shutdown_path.stdout }}']

- name: Cleanup installation
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Stop ephemeral PXE server
      ansible.builtin.import_role:
        name: pxe_server
        tasks_from: stop

