# vim: ft=yaml.ansible
---
- name: Print unconfigured nodes informations
  hosts: all
  gather_facts: false
  tasks:
    - name: Wake up node
      when: mac is defined
      community.general.wakeonlan:
        mac: '{{ mac }}'
      delegate_to: localhost

    - name: Wait for the node to be reachable
      ansible.builtin.wait_for_connection:
        connect_timeout: 1
        timeout: 600

    - name: Gather facts
      ansible.builtin.setup:

    - name: Gather devices information
      ansible.builtin.command:
        cmd: lsblk -a -o NAME,SIZE,TYPE,ID-LINK,PARTLABEL,PARTUUID,FSTYPE,LABEL,UUID,FSUSED,MOUNTPOINTS
        creates:
      register: devices_pretty

    - name: Gather hardware configuration
      become: true
      ansible.builtin.command:
        cmd: nixos-generate-config --no-filesystems --show-hardware-config
        creates:
      register: hardware_config

    - name: Print Architecture
      ansible.builtin.debug:
        var: ansible_facts.architecture

    - name: Print devices
      ansible.builtin.debug:
        var: devices_pretty.stdout_lines

    - name: Print hardware configuration
      ansible.builtin.debug:
        var: hardware_config.stdout_lines
