# vim: ft=yaml.ansible
---
- name: Generate a temporary SSH key for the install
  gather_facts: false
  hosts: localhost

  tasks:
    - name: Generate keypair
      community.crypto.openssh_keypair:
        path: '{{ playbook_dir }}/archiso_ssh.key'
        size: 384
        type: ecdsa
        # mode: '0400'
      register: ssh_key

- name: Start temporary PXE server
  hosts: localhost

  roles:
    - role: pxe_server
      vars:
        pxe_server_enabled: true
        pxe_server_ssh_authorized_key: '{{ ssh_key.public_key }}'

- name: Provision bare metal machines
  gather_facts: false
  hosts: nodes

  tasks:
    - name: Wake machines
      community.general.wakeonlan:
        mac: '{{ mac }}'
      delegate_to: localhost

    - name: Wait for machine to be reachable
      ansible.builtin.wait_for_connection:
        connect_timeout: 1
        timeout: 600

- name: Cleanup temporary PXE server
  gather_facts: false
  hosts: localhost

  roles:
    - role: pxe_server
      vars:
        pxe_server_enabled: false
