# vim: ft=yaml.ansible
---
- name: Wakeup nodes
  gather_facts: false
  hosts: nodes

  tasks:
    - name: Send WoL packet
      community.general.wakeonlan:
        mac: '{{ mac }}'
      delegate_to: localhost

    - name: Wait for machine to wake up
      ansible.builtin.wait_for_connection:

- name: Fix/Finalize Archlinux install
  hosts: nodes

  roles:
    - role: archlinux_base
      vars:
        archlinux_base_svc_account_authorized_key: '{{ lookup("file", playbook_dir + "/service_account.key.pub") }}'
        archlinux_base_root_dev: '{{ disks.boot }}-part2'
        archlinux_base_snapshot_retention: 12h 7d 4w
    - role: archlinux_storage
      vars:
        archlinux_storage_pools: '{{ storage_pools }}'
    - role: archlinux_k3s
      vars:
        archlinux_k3s_package: k3s-1.28-bin
        archlinux_k3s_root_dev: '{{ disks.boot }}-part2'
