{
 "title": "Cluster Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptimes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(kubernetes_node, device) (node_filesystem_size_bytes{fstype=\"btrfs\"} - node_filesystem_avail_bytes{fstype=\"btrfs\"})",
     "legendFormat": "{{kubernetes_node}} ({{device}}) - Used"
    },
    {
     "expr": "sum by(kubernetes_node, device) (node_filesystem_avail_bytes{fstype=\"btrfs\"})",
     "legendFormat": "{{kubernetes_node}} ({{device}}) - Free"
    }
   ]
  },
  {
   "title": "Active Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kubelet_running_pods)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(scheduler_pending_pods)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Traffic",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code) (rate(traefik_entrypoint_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Server requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Summary",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(1.0 - rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) / count(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "RAM"
    },
    {
     "expr": "(sum(max by(device) (node_filesystem_size_bytes{fstype=\"btrfs\"})) - (sum(max by(device) (node_filesystem_free_bytes{fstype=\"btrfs\"})))) / sum(max by(device) (node_filesystem_size_bytes{fstype=\"btrfs\"}))",
     "legendFormat": "Disk"
    }
   ]
  },
  { "title": "Node CPU / RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Cluster CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1.0 - rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])",
     "legendFormat": "{{kubernetes_node}}/core/{{cpu}}"
    }
   ]
  },
  {
   "title": "Cluster RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(kubernetes_node) (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)",
     "legendFormat": "{{kubernetes_node}}"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Pods CPU/RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Pods CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "mcpu" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[$__rate_interval])) by (namespace,pod)) * 1000",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Pods RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\"}) by (namespace, pod)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}