---
apiVersion: v1
kind: Service
metadata:
  name: authelia
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9959'
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9091
      protocol: TCP
      targetPort: http
    - name: metrics
      port: 9959
      protocol: TCP
      targetPort: metrics
