# vim: ft=yaml.ansible
---
- name: Create ansible user
  become: true
  ansible.builtin.command:
    cmd: >
      arch-chroot /mnt useradd
        --comment 'Ansible service account'
        --create-home
        --system
        ansible
    creates: /mnt/home/ansible

- name: Get ansible user UID
  become: true
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      arch-chroot /mnt getent passwd ansible | cut -d: -f3
    executable: /bin/bash
    creates: # nothing
  register: svc_acc_uid

- name: Get ansible user GID
  become: true
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      arch-chroot /mnt getent passwd ansible | cut -d: -f4
    executable: /bin/bash
    creates: # nothing
  register: svc_acc_gid

- name: Add authorized_key to ansible user
  become: true
  ansible.builtin.lineinfile:
    path: /mnt/home/ansible/.ssh/authorized_keys
    search_string: '{{ archlinux_setup_ansible_account_ssh_authorized_key }}'
    line: '{{ archlinux_setup_ansible_account_ssh_authorized_key }}'
    create: true
    owner: '{{ svc_acc_uid.stdout }}'
    group: '{{ svc_acc_gid.stdout }}'
    mode: '0600'
    state: present

- name: Grant the ansible user passwordless sudo
  become: true
  ansible.builtin.copy:
    dest: /mnt/etc/sudoers.d/ansible-nopasswd
    content: 'ansible ALL=(ALL:ALL) NOPASSWD: ALL'
    mode: '0400'
