# vim: ft=yaml.ansible
---
- name: Create service account
  ansible.builtin.user:
    name: ansible
    comment: Ansible system account
    password: '!'
    create_home: true
    move_home: true
    state: present

- name: Add service account ssh key
  ansible.posix.authorized_key:
    user: ansible
    key: '{{ archlinux_base_svc_account_authorized_key }}'
    state: present

- name: Grant the service account passwordless sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/ansible-nopasswd
    content: 'ansible ALL=(ALL:ALL) NOPASSWD: ALL'
    mode: '0400'
    validate: visudo -cf %s

- name: Ensure SSHD is enabled
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true
