{
 "title": "Cluster Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptimes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by(node, device) (node_filesystem_size_bytes{fstype=\"btrfs\"} - node_filesystem_avail_bytes{fstype=\"btrfs\"})",
     "legendFormat": "{{node}} ({{device}}) - Used"
    },
    {
     "expr": "max by(node, device) (node_filesystem_avail_bytes{fstype=\"btrfs\"})",
     "legendFormat": "{{node}} ({{device}}) - Free"
    }
   ]
  },
  {
   "title": "Active Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kubelet_running_pods)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Problematic Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_working_pods) - sum(kubelet_desired_pods) + sum(scheduler_unschedulable_pods)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_size_sum[$__rate_interval]))",
     "legendFormat": "Ingress"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_response_size_sum[$__rate_interval]))",
     "legendFormat": "Egress"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[$__rate_interval]))",
     "legendFormat": "Internal"
    }
   ]
  },
  {
   "title": "Cluster Summary",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_cpu_seconds_total{mode!=\"idle\"}) / sum(node_cpu_seconds_total)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "RAM"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{fstype=\"btrfs\"}) - sum(node_filesystem_free_bytes{fstype=\"btrfs\"})) / sum(node_filesystem_size_bytes{fstype=\"btrfs\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "API Server requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[60s])) * 60s",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Traffic (1h)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"[123][0-9][0-9]\"}[60m])) * 60s",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"[45][0-9][0-9]\"}[60m])) * 60s",
     "legendFormat": "Error"
    }
   ]
  },
  { "title": "Node CPU / RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cluster CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1.0 - rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])",
     "legendFormat": "{{node}}/{{cpu}}"
    }
   ]
  },
  {
   "title": "Cluster RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(node) (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max by(node) (node_memory_MemTotal_bytes))",
     "legendFormat": "Capacity"
    }
   ]
  },
  { "title": "Pods CPU/RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Pods CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "mcpu" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[$__rate_interval])) by (namespace,pod)) * 1000",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Pods RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{container!=\"\"}) by (namespace, pod)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}