---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minecraft-data
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-data
labels:
    app.kubernetes.io/name: minecraft-data
spec:
  capacity: 50Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteOncePod]
  storageClassName: minecraft-data
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/rootfs/@minecraft
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - coruscant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  labels:
    app.kubernetes.io/name: minecraft-data
spec:
  accessModes: [ReadWriteOncePod]
  storageClassName: minecraft-data
  resources:
    requests:
      storage: 50Gi
