---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app.kubernetes.io/name: minecraft
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft
  replicas: 1
  revisionHistoryLimit: 2
  serviceName: minecraft

  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft
    spec:
      containers:
        - name: minecraft
          image: minecraft-itzg
          env:
            - { name: TZ, value: Europe/Paris }
            - { name: INIT_MEMORY, value: 4G }
            - { name: MAX_MEMORY, value: 10G }
            - { name: EULA, value: 'true' }
            - { name: VERSION, value: 1.7.10 }
            - { name: OVERRIDE_SERVER_PROPERTIES, value: 'true' }
            - { name: MOTD, value: QG des xX_g@ym€rs_Xx }
            - { name: DIFFICULTY, value: '2' }
            - { name: VIEW_DISTANCE, value: '16' }

            - { name: OVERRIDE_WHITELIST, value: 'true' }
            - { name: WHITELIST, value: icanwalkonwater }

            - { name: OVERRIDE_OPS, value: 'true' }
            - { name: OPS, value: icanwalkonwater }

            - { name: ENABLE_AUTOPAUSE, value: 'true' }
            - { name: AUTOPAUSE_TIMEOUT_EST, value: '1200' }
            - { name: MAX_TICK_TIME, value: '-1' }

            - { name: SETUP_ONLY, value: 'false' }
            - { name: TYPE, value: CUSTOM }
            - { name: CUSTOM_SERVER, value: /data/lwjgl3ify-forgePatches.jar }
            - { name: JVM_OPTS, value: '@/data/java9args.txt' }
          ports:
            - { name: minecraft, containerPort: 25565 }
          volumeMounts:
            - name: storage
              mountPath: /data
          resources:
            requests: { memory: 4Gi }
            limits: { memory: 10.1Gi }

  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: [ReadWriteOncePod]
        storageClassName: minecraft-data
        resources:
          requests: { storage: 50Gi }
