services:
  gtnh:
    build:
      context: .
      args:
        - GTNH_VERSION=2.7.4
    ports:
      - 25565:25565
    environment:
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
      EULA: 'true'
      SEED: '1293967824733727157'
      DIFFICULTY: '2'
      MOTD: 'GregTech: Nuwu Horizowos'
      VIEW_DISTANCE: '32'

    volumes:
      - ../data/whitelist.json:/minecraft/whitelist.json:ro
      - ../data/ops.json:/minecraft/ops.json:ro
      - mc-world:/minecraft/World
      - mc-backups:/minecraft/backups

volumes:
  mc-world:
  mc-backups:
