#!/bin/sh

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER grafana WITH ENCRYPTED PASSWORD '$(cat $X_GRAFANA_PASSWORD_FILE)' NOCREATEDB;
	CREATE DATABASE grafana OWNER grafana;
	GRANT ALL PRIVILEGES ON DATABASE grafana TO grafana;
EOSQL
