#!/bin/sh

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER authelia WITH ENCRYPTED PASSWORD '$(cat $X_AUTHELIA_PASSWORD_FILE)' NOCREATEDB;
	CREATE DATABASE authelia OWNER authelia;
	GRANT ALL PRIVILEGES ON DATABASE authelia TO authelia;
EOSQL
