#!/bin/sh

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER lldap WITH ENCRYPTED PASSWORD '$(cat $X_LLDAP_PASSWORD_FILE)' NOCREATEDB;
	CREATE DATABASE lldap OWNER lldap;
	GRANT ALL PRIVILEGES ON DATABASE lldap TO lldap;
EOSQL
