---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy: { type: Recreate }

  template:
    spec:
      containers:
        - name: immich-server
          image: immich-server
          env:
            - { name: TZ, value: Europe/Paris }
            - { name: CPU_CORES, value: '2' }
            - { name: REDIS_HOSTNAME, value: 'redis.immich.svc' }
            - { name: REDIS_PORT, value: '6379' }


            - { name: DB_HOSTNAME, value: 'postgres.immich.svc' }
            - { name: DB_USERNAME_FILE, value: /var/run/secrets/icanwalkonwater.dev/db-username }
            - { name: DB_PASSWORD_FILE, value: /var/run/secrets/icanwalkonwater.dev/db-password }
            - { name: DB_DATABASE_NAME_FILE, value: /var/run/secrets/icanwalkonwater.dev/db-database-name }
          ports:
            - { name: http, containerPort: 2283 }
          volumeMounts:
            - name: data
              mountPath: /data
            - name: credentials
              mountPath: /var/run/secrets/icanwalkonwater.dev
              readOnly: true
          resources:
            requests: { cpu: 1000m, memory: 1Gi }
            limits: { cpu: 2000m, memory: 2Gi }

          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5

      volumes:
        - name: data
          persistentVolumeClaim: { claimName: immich-data-pvc }
        - name: credentials
          secret:
            secretName: immich-server-credentials
            items:
              - { key: DB_USERNAME, path: db-username }
              - { key: DB_PASSWORD, path: db-password }
              - { key: DB_DATABASE_NAME, path: db-database-name }
