---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: octoprint
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
  - host: octoprint.homelab.icanwalkonwater.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: { name: octoprint, port: { number: 5000 } }
  tls:
  - hosts:
    - octoprint.homelab.icanwalkonwater.dev
    secretName: octoprint-tls
