---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: octoprint
resources:
  - statefulset.yml
  - service.yml
  - ingress.yml

images:
  - name: octoprint
    newName: docker.io/octoprint/octoprint:canary
    digest: sha256:1ef4c0ff7d85c221e9225fc72d4aafee526f2d7b934d60b553db348f9e4aa859
