---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: immich-machine-learning
    includeTemplates: true
    includeSelectors: true
  - pairs:
      app.kubernetes.io/component: machine-learning
    includeTemplates: true

resources:
  - deployment.yml
  - service.yml
