FROM golang:1.21-alpine AS builder

RUN apk add git
RUN mkdir -p /pixiecore &&\
    git clone --branch main --depth 1 https://github.com/danderson/netboot.git /netboot

WORKDIR /netboot
RUN go install -v ./cmd/pixiecore

FROM scratch
COPY --from=builder /go/bin/pixiecore /pixiecore

ENTRYPOINT ["/pixiecore"]

