---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

namespace: ingress-redirects
resources:
  - namespace.yml
  - ingress.yml
