---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: prometheus
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: node-exporter
  ports:
    - name: http
      port: 9100
      targetPort: http
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: node-exporter
          args:
            - --path.rootfs=/host/rootfs
            - --path.sysfs=/host/sysfs
            - --path.procfs=/host/procfs
          ports:
            - containerPort: 9100
              name: http
          resources:
            requests: { cpu: 100m, memory: 100Mi }
            limits: { cpu: 1000m, memory: 100Mi }
          volumeMounts:
            - name: rootfs
              mountPath: /host/rootfs
              mountPropagation: HostToContainer
              readOnly: true
            - name: sysfs
              mountPath: /host/sysfs
              mountPropagation: HostToContainer
              readOnly: true
            - name: procfs
              mountPath: /host/procfs
              mountPropagation: HostToContainer
              readOnly: true
      volumes:
        - name: rootfs
          hostPath: { path: / }
        - name: sysfs
          hostPath: { path: /sys }
        - name: procfs
          hostPath: { path: /proc }
