---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - { name: redis, containerPort: 6379 }
          resources:
            requests: { cpu: 50m, memory: 16Mi }
            limits: { cpu: 200m, memory: 32Mi }
