# vim: ft=yaml.ansible
---
- name: Partition disks
  ansible.builtin.include_tasks:
    file: partition_table.yml
  loop: '{{ disk_setup_spec.partitionTables }}'
  loop_control:
    label: '{{ item.device }}'

- name: Create filesystems
  ansible.builtin.include_tasks:
    file: filesystem.yml
  loop: '{{ disk_setup_spec.fileSystems }}'
  loop_control:
    label: '{{ item.type }} on {{ item.devices }}'

- name: Mount filesystems
  ansible.builtin.include_tasks:
    file: mountpoint.yml
  loop: '{{ disk_setup_spec.mountPoints }}'
  loop_control:
    label: '{{ item.device }} on {{ item.mountPoint }}'
