# vim: ft=yaml.ansible
---
- name: Generate fstab
  become: true
  ansible.builtin.shell:
    cmd: genfstab -U /mnt >> /mnt/etc/fstab
    creates: # nothing

- name: Set timezone to Europe/Paris
  become: true
  ansible.builtin.command:
    cmd: arch-chroot /mnt ln -sf /usr/share/zoneinfo/Europe/Paris /etc/localtime
    creates: /mnt/etc/localtime

- name: Adjust harware clock
  become: true
  ansible.builtin.command:
    cmd: arch-chroot /mnt hwclock --systohc
    creates: # nothing

- name: Specify locale to generate
  become: true
  ansible.builtin.lineinfile:
    path: /mnt/etc/locale.gen
    search_string: en_US.UTF-8
    line: en_US.UTF-8 UTF-8
    state: present

- name: Generate locales
  become: true
  ansible.builtin.command:
    cmd: arch-chroot /mnt locale-gen
    creates: # too complicated

- name: Set LANG
  become: true
  ansible.builtin.copy:
    dest: /mnt/etc/locale.conf
    content: LANG=en_US.UTF-8
    mode: '0644'

- name: Set console keyboard layout
  become: true
  ansible.builtin.copy:
    dest: /mnt/etc/vconsole.conf
    content: KEYMAP=fr
    mode: '0644'

- name: Set hostname
  become: true
  ansible.builtin.copy:
    dest: /mnt/etc/hostname
    content: '{{ inventory_hostname }}'
    mode: '0644'
