---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-fast
provisioner: rancher.io/local-path
parameters:
  nodePath: /var/lib/rancher/k3s/storage
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-slow
provisioner: rancher.io/local-path
parameters:
  nodePath: /mnt/lucastrunk/@k3s/@storage
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
