---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

generatorOptions:
  immutable: true

namespace: kube-system
resources:
  - ingress-nginx.yml
  - cert-manager.yml
