---
apiVersion: v1
kind: Service
metadata:
  name: exporter
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7979
      protocol: TCP
      targetPort: http
