---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBNBC3GaRqVk8PSpELQGg9rkSCBQwkcElQ4Rtm4hSUgugC1H36Vus+YT3hWOVFKlZdoV5F7++X2MjLtdXwMQrCEp5G+ysaeyu3pbjpLkmeiz+Nldm4NO0QyvdDOvKDWJsm6Qu8k4G1+QCwlUkczc0/V3RlrgnFYw7MViejRohFG80Z63bYG9YrqO411dxKVBQMliVdSHft5p/FzG3oe6qwcmHy9v3vY4Wnlp5XDgIQNlsvsgsmzqjLJ+GTn6sMA3kEmapFWGj4ortVK3OauNTAxZl1vue4k3aiND15zdy2e3VuXgcAqEhihWJEGFwejga+OW8gOovKjfS5ZxGf08qiQsqaYV9fzHUyigrbVXmz6LYqWW7jNgT6/AhvY5Yt3KY4Ar3ZNeumgyQWpmiwFF2hC2XLzNK9gazs4GIue3s0OGj74Z3JJOmwGjwMJktB11SYLGuWBJhPtkEQ4/evotk5ovkI2FgiSNtUvGYqxiuNfeI4WzIOUNArZ7E63//mlZBGDLAlRrhELrgOx6+1p3R5x2SmJLhKyh8bmVFCKcuf81vYLma9PuL+fD92cocUzmFs9l4eC+N2feASj1mdJ4DNe1kc7lxf+P1FNg8OBcl54+5z3z369S2n7hK7Bizp5OoM1f5yZ/5bkjo5/HEvrNxmLU4yf0mSlKvoTCqPDAKLCei5iaeweO4/DaspCHePxL0G4pDZxwAUn7pBc8+Ac5Fz5fPk4QKCueDEoABgFRmGjeozeQEB36sPC
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
