---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  replicas: 1

  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
    spec:
      containers:
        - name: prometheus
          image: docker.io/prom/prometheus:v2.51.2
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --log.level=debug
          ports:
            - containerPort: 9090
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
              readOnly: true
            - name: storage
              mountPath: /prometheus
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
      volumes:
        - name: config
          configMap:
            name: prometheus-cm
            items:
              - key: prometheus.yml
                path: prometheus.yml
      serviceAccountName: prometheus

  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: [ReadWriteOncePod]
        storageClassName: local-path-slow
        resources:
          requests:
            storage: 100Gi
