---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: jellyfin
    includeTemplates: true
    includeSelectors: true
  - pairs:
      app.kubernetes.io/component: jellyfin
    includeTemplates: true

namespace: jellyfin
resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - pv-data.yml
  - pv-media.yml
