---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
  labels:
    app.kubernetes.io/name: lldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lldap
  replicas: 1

  template:
    metadata:
      labels:
        app.kubernetes.io/name: lldap
    spec:
      containers:
      - name: lldap
        image: ghcr.io/lldap/lldap:2020-09-08-alpine-rootless
        env:
          - name: TZ
            value: Europe/Paris
          - name: LLDAP_LDAP_BASE_CN
            value: dc=homelab,dc=icanwalkonwater,dc=dev
        ports:
          - name: ldap
            containerPort: 3890
          - name: ldaps
            containerPort: 6360
          - name: http
            containerPort: 17170
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
---

