---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: lldap
    includeTemplates: true
    includeSelectors: true
  - pairs:
      app.kubernetes.io/component: ldap
    includeTemplates: true

namespace: auth
resources:
  - deployment.yml
  - pv.yml
  - service.yml

secretGenerator:
  - name: lldap-credentials
    options:
      disableNameSuffixHash: true
    envs:
      - lldap-credentials.env
