---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth
resources:
  - deployment.yml
  - service.yml
  - pv.yml

secretGenerator:
  - name: lldap-credentials
    options:
      disableNameSuffixHash: true
    envs:
      - lldap-credentials.env
