---
apiVersion: v1
kind: Service
metadata:
  name: lldap
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lldap
  ports:
    - name: ldap
      protocol: TCP
      targetPort: ldap
    - name: ldaps
      protocol: TCP
      targetPort: ldaps
    - name: http
      protocol: TCP
      targetPort: http
