# vim: ft=yaml.ansible
---
- name: Install bootloader packages
  become: true
  ansible.builtin.command:
    cmd: pacstrap -M /mnt {{ item }}
    creates: # nothing
  loop:
    - grub
    - efibootmgr

- name: Install grub
  become: true
  ansible.builtin.command:
    cmd: arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB --removable
    creates: # too tricky

- name: Generate grub.cfg
  become: true
  ansible.builtin.command:
    cmd: arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
    creates: # regenerate every time
