---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  local:
    path: /mnt/lucastrunk/@media/@storage
  capacity: { storage: 1000G }
  accessModes: [ReadOnlyMany]
  storageClassName: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [coruscant]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
spec:
  volumeName: jellyfin-media-pv
  storageClassName: ''
  accessModes: [ReadOnlyMany]
  resources: { requests: { storage: 1000G } }
