---
version: '3.8'

x-scale-0-by-default:
  &scale0
  deploy:
    replicas: 0

services:

  # === Web
  # - Caddy (reverse proxy)

  web-caddy:
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    networks:
      - web-external
      - web-internal
      - web-meta

  # === Databases
  # Postgres

  db-postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: yay
      PGDATA: /var/lib/postgresql/data
      X_GRAFANA_PASSWORD_FILE: /run/secrets/postgres_grafana_password
      X_LLDAP_PASSWORD_FILE: /run/secrets/postgres_lldap_password
      X_AUTHELIA_PASSWORD_FILE: /run/secrets/postgres_authelia_password
    secrets:
      - postgres_grafana_password
      - postgres_lldap_password
      - postgres_authelia_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/create-grafana-user.sh:/docker-entrypoint-initdb.d/create-grafana-user.sh:ro
      - ./postgres/create-lldap-user.sh:/docker-entrypoint-initdb.d/create-lldap-user.sh:ro
      - ./postgres/create-authelia-user.sh:/docker-entrypoint-initdb.d/create-authelia-user.sh:ro
    networks:
      - db

  # === Analytics
  # - Grafana
  # - Prometheus
  #   - Node exporter
  #   - Cadvisor

  analytics-grafana:
    image: grafana/grafana-oss:10.0.0
    restart: unless-stopped
    depends_on:
      - db-postgres
      - analytics-prometheus
    environment:
      GF_SERVER_ROOT_URL: https://grafana.homelab.icanwalkonwater.dev
      GF_DEFAULT_INSTANCE_NAME: lucaslab
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: db-postgres
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD__FILE: /run/secrets/postgres_grafana_password
      GF_ANALYTICS_REPORTING_ENABLED: false
      GF_ANALYTICS_CHECK_FOR_UPDATES: false
      GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES: false
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: false
      GF_SECURITY_DISABLE_GRAVATAR: true
      GF_SECURITY_COOKIE_SECURE: true
      GF_SECURITY_STRICT_TRANSPORT_SECURITY: true
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/general.json
      GF_ALTERTING_ENABLED: false
      GF_UNIFIED_ALERTING_ENABLED: false
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_SIGNOUT_REDIRECT_URL: https://auth.homelab.icanwalkonwater.dev/logout
      GF_AUTH_BASIC_ENABLE: false
      GF_AUTH_PROXY_ENABLED: true
      GF_AUTH_PROXY_HEADER_NAME: X-Webauth-Users
      GF_AUTH_PROXY_AUTO_SIGN_UP: true
      GF_AUTH_PROXY_HEADERS: Name:X-Webauth-Name Email:X-Webauth-Email Groups:X-Webauth-Groups
    secrets:
      - postgres_grafana_password
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - grafana-data:/var/lib/grafana
    networks:
      - analytics
      - db
      - web-internal

  analytics-prometheus:
    image: prom/prometheus:v2.44.0
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - analytics

  analytics-exporter-node:
    image: prom/node-exporter:v1.6.0
    restart: unless-stopped
    pid: host
    command:
      - '--collector.disable-defaults'
      - '--collector.cpu'
      - '--collector.diskstats'
      - '--collector.edac'
      - '--collector.filesystem'
      - '--collector.zfs'
      - '--collector.hwmon'
      - '--collector.loadavg'
      - '--collector.meminfo'
      - '--collector.netclass'
      - '--collector.netdev'
      - '--collector.netstat'
      - '--collector.nvme'
      - '--collector.os'
      - '--collector.powersupplyclass'
      - '--collector.stat'
      - '--collector.thermal_zone'
      - '--collector.time'
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - analytics

  analytics-exporter-cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    restart: unless-stopped
    command:
      - '-housekeeping_interval=15s'
      - '-docker_only=true'
      - '--disable_metrics=disk,network,tcp,udp,percpu,sched,process,referenced_memory'
    volumes:
      - '/:/host:ro'
      - '/run/user/1000/docker.sock:/var/run/docker.sock:ro'
      - '/sys:/sys:ro'
      - '~/.local/share/docker:/home/lucas/.local/share/docker:ro'
    networks:
      - analytics

  # === Auth
  # - LLDAP
  # - Authelia

  auth-lldap:
    image: nitnelave/lldap:v0.4.3-alpine
    restart: always
    depends_on:
      - db-postgres
    environment:
      TZ: Europe/Paris
      LLDAP_JWT_SECRET_FILE: /run/secrets/lldap_jwt_secret
      LLDAP_LDAP_USER_PASS_FILE: /run/secrets/lldap_admin_pass
      LLDAP_LDAP_BASE_DN: dc=homelab,dc=icanwalkonwater,dc=dev
      LLDAP_SMTP_OPTIONS_ENABLE_PASSWORD_RESET: false
      LLDAP_LDAPS_OPTIONS_ENABLED: false
      LLDAP_DATABASE_URL: postgres://lldap:lldap@db-postgres/lldap
    secrets:
      - lldap_jwt_secret
      - lldap_admin_pass
    volumes:
      - lldap-data:/data
    networks:
      - auth
      - db
      - web-internal

  auth-authelia:
    image: authelia/authelia:4.37.5
    restart: always
    depends_on:
      - db-postgres
      - auth-lldap
    environment:
      AUTHELIA_JWT_SECRET_FILE: /run/secrets/authelia_jwt_secret
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/authelia_session_secret
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/authelia_storage_encryption_secret
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /run/secrets/postgres_authelia_password
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_storage_encryption_secret
      - postgres_authelia_password
    volumes:
      - ./authelia/configuration.yml:/config/configuration.yml:ro
    networks:
      - db
      - auth
      - web-internal
      - authelia-outside

  # === Octoprint
  # Stopped by default

  octoprint:
    image: octoprint/octoprint:1.9.0-minimal
    restart: unless-stopped
    <<: *scale0
    deploy:
      replicas: 0
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - octoprint-data:/octoprint
    networks:
      - web-internal

volumes:
  caddy-data:

  postgres-data:

  grafana-data:
  prometheus-data:

  lldap-data:

  octoprint-data:


networks:
  analytics:
    internal: true
  auth:
    internal: true

  # Network with internet access so authelia can reach the NTP server
  authelia-outside:

  web-external:
  web-internal:
    internal: true
  web-meta:
    external: true

  db:
    internal: true

secrets:
  lldap_jwt_secret:
    file: ./lldap/jwt_secret.txt
  lldap_admin_pass:
    file: ./lldap/admin_pass.txt

  authelia_jwt_secret:
    file: ./authelia/jwt_secret.txt
  authelia_session_secret:
    file: ./authelia/session_secret.txt
  authelia_storage_encryption_secret:
    file: ./authelia/storage_encryption_secret.txt

  postgres_grafana_password:
    file: ./grafana/postgres_password.txt
  postgres_lldap_password:
    file: ./lldap/postgres_password.txt
  postgres_authelia_password:
    file: ./authelia/postgres_password.txt
