apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: auth
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.authelia.com
    chart: authelia
    targetRevision: 0.9.5
    helm:
      valuesObject:
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-staging
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          tls:
            enabled: true
            secret: authelia-tls
        configMap:
          enable: true
          session:
            cookies:
              - domain: homelab.icanwalkonwater.dev
                subdomain: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
