---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: auth
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/icanwalkonwater/homelab
    targetRevision: HEAD
    path: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
