apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.17.2
    helm:
      parameters:
      - name: crds.enabled
        value: 'true'
      - name: resources
        value:
          requests: { cpu: 10m, memory: 64Mi }
          limits: { cpu: 1000m, memory: 128Mi }
      - name: cainjector.resources
        value:
          requests: { cpu: 10m, memory: 64Mi }
          limits: { cpu: 1000m, memory: 128Mi }
      - name: webhook.resources
        value:
          requests: { cpu: 10m, memory: 64Mi }
          limits: { cpu: 1000m, memory: 128Mi }
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
