apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.17.2
    helm:
      parameters:
      - name: crds.enabled
        value: 'true'
      - { name: resources.requests.cpu, value: 10m }
      - { name: resources.limits.cpu, value: 1000m }
      - { name: resources.requests.memory, value: 64Mi }
      - { name: resources.limits.memory, value: 128Mi }

      - { name: cainjector.resources.requests.cpu, value: 10m }
      - { name: cainjector.resources.limits.cpu, value: 1000m }
      - { name: cainjector.resources.requests.memory, value: 64Mi }
      - { name: cainjector.resources.limits.memory, value: 128Mi }

      - { name: webhook.resources.requests.cpu, value: 10m }
      - { name: webhook.resources.limits.cpu, value: 1000m }
      - { name: webhook.resources.requests.memory, value: 64Mi }
      - { name: webhook.resources.limits.memory, value: 128Mi }
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
