---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-gtnh
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: minecraft-gtnh
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/icanwalkonwater/homelab
    targetRevision: HEAD
    path: minecraft-gtnh
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
