---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: selead-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://bitnami-labs.github.io
    chart: sealed-secrets
    targetRevision: v2.16.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
