---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: postgres
    includeTemplates: true
    includeSelectors: true
  - pairs:
      app.kubernetes.io/component: database
    includeTemplates: true

resources:
  - deployment.yml
  - service.yml
